#!/bin/bash

# Function to provide help for modifying an existing user
function modify_user_help() {
    echo "----------------------------------------------"
    echo "           🛠️  Help: Modify an Existing User"
    echo "----------------------------------------------"
    echo "This option allows you to modify an existing user’s details, such as their home directory or default shell."
    echo "Usage:"
    echo "  You will be prompted to enter the username of the user to modify."
    echo "  Then, you can modify specific attributes like their shell, home directory, or group."
    echo ""
    echo "Commands used:"
    echo "  - usermod <options> <username>: This command is used to modify user details."
    echo ""
    echo "Options for usermod:"
    echo "  - -d <directory>: Change the user's home directory."
    echo "  - -s <shell>: Change the user's login shell (e.g., /bin/bash)."
    echo "  - -g <group>: Change the user's primary group."
    echo "  - -aG <group>: Add the user to a secondary group."
    echo ""
    echo "Example Usage:"
    echo "  - Change a user's shell to /bin/bash:"
    echo "      sudo usermod -s /bin/bash john"
    echo ""
    echo "  - Change a user's home directory:"
    echo "      sudo usermod -d /new/home/directory john"
    echo ""
    echo "  - Add a user to an additional group:"
    echo "      sudo usermod -aG developers john"
    echo ""
    echo "Make sure you have root or sudo privileges before running this command."
    echo "----------------------------------------------"
}
